name: "Budget Assistant"
version: "1.1.0-categories-final"
slug: "budget_assistant"
description: "Gestion de budget Offline-First bas√©e sur PocketBase"
arch:
  - aarch64
  - amd64
ports:
  8090/tcp: 8090
map:
  - "share:rw"
data: true # Obligatoire pour la persistance
