name: "BudgetTime"
version: "1.8.5"
slug: "budgettime"
description: "Gestion de budget Offline-First bas√©e sur PocketBase"
url: "https://github.com/hkdone/budgettime"
startup: application
arch:
  - aarch64
  - amd64
  - armhf
  - armv7

map:
  - "share:rw"
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: Web Interface
data: true # Persistance dans /data
options: {}
schema: {}
